### ISSUE TITLE
/predict command fails

### ISSUE THREAD

**Issue by BadWolf1023** [BadWolf1023/MKW-Table-Bot#186]
The `/predict` command now fails because TinyURL implemented Cloudflare protection. Originally, we needed to shorten URLs due to a Discord UI bug, but we do not need to shorten them anymore. Therefore, remove all code that shortens URLs and simply use the full URL.

Additionally, for Lounge table submissions, update this field title to “Preview Link” (as oppose to “Short Preview Link”):
![image](https://github.com/BadWolf1023/MKW-Table-Bot/assets/23650362/2511db42-f8b4-4576-8b88-dd040a3d9d97)

**Comment by rkj43** [comment]
Hello.
I am beginner and I would like to try to fix this!
Could you assign this to me please?
