### ISSUE TITLE
Update /record command to filter by RTs or CTs

### ISSUE THREAD

**Issue by BadWolf1023** [BadWolf1023/MKW-Table-Bot#187]
`/record` displays a player's record against another player. This record includes all races played, including RTs and CTs.

We want to change `/record` to two commands: `/record track_type:RT` and `/record track_type:CT`

`/record track_type:RT` will display a players record against another player for RTs only
`/record track_type:CT` will display a players record against another player for CTs only

This will require a change to a a SQLite query, so knowledge of an SQL dialect variant is recommended. (eg PostgreSQL, MySQL, SQLite etc.)

**Comment by camelwater** [comment]
#192
