### ISSUE TITLE
Some table submissions fail to send

### ISSUE THREAD

**Issue by BadWolf1023** [BadWolf1023/MKW-Table-Bot#201]
When we removed URL shortening, some URLs are now too long and fail to send. Discord limits the length of links in fields. However, they have a much higher limit for links in embed descriptions, which is how Table Bot has always sent long links (Lorenzi table edit links and table submission preview links). See the pictures below for the desired changes.

![image](https://github.com/BadWolf1023/MKW-Table-Bot/assets/23650362/5aa850b1-cb8e-4a6d-9cc6-65545558ee93)

![image](https://github.com/BadWolf1023/MKW-Table-Bot/assets/23650362/b61e2c4e-aa34-4506-9e90-26889661e4b7)

![image](https://github.com/BadWolf1023/MKW-Table-Bot/assets/23650362/6ee8120b-38b7-4d41-a577-63a6ea3fcc3a)

**Comment by Fear-MK** [comment]
Are you sure that the prediction command needs to be changed? its a url parameter when setting the embed, not a field afaik. Do not know if the same rules apply

**Comment by BadWolf1023** [comment]
> Are you sure that the prediction command needs to be changed? its a url parameter when setting the embed, not a field afaik. Do not know if the same rules apply
> 
> 

@Fear-MK I'm not sure.

**Comment by BadWolf1023** [comment]
> > Are you sure that the prediction command needs to be changed? its a url parameter when setting the embed, not a field afaik. Do not know if the same rules apply
> > 
> > 
> 
> @Fear-MK I'm not sure.


field value (used for "Preview Link") = 1024
description = 4096
embed url (predict command) = Unknown

The sum of all characters in the embed should be less than or equal to 6000.

**Comment by Fear-MK** [comment]
I will test it later
