### ISSUE TITLE
Backup table generator fails and causes internal bot error

### ISSUE THREAD

**Issue by BadWolf1023** [BadWolf1023/MKW-Table-Bot#206]
This is a twofold problem. First, we need to fix the backup table generator (perhaps we are missing a package). Secondly, IF the backup table generator fails, we should catch it. It seems we don't properly detect when it does fail.

![image](https://github.com/BadWolf1023/MKW-Table-Bot/assets/23650362/b7e7e305-af27-4417-9cbc-b6292588711f)

**Comment by camelwater** [comment]
closed in #211
