### ISSUE TITLE
Discord Interactions Support

### ISSUE THREAD

**Issue by camelwater** [BadWolf1023/MKW-Table-Bot#81]
Discord's changes to `message content` as a privileged intent that must be applied for will mean that MKW Table Bot commands will no longer work - these changes will come into effect in April 2022.

In anticipation of these changes, I have begun working on implementing MKW Table Bot commands as slash commands, and implementing Discord Buttons.

The easiest way to migrate would be to implement all commands as slash commands, so that the codebase would stay relatively the same, as Buttons and Select Menus have limited functionality. But for some commands and situations, `discord.ui` Components will probably be much better.

As `discord.py` has been discontinued, the Discord API dependency will be changing to `py-cord`; it supports the new Discord Components and is the most active Python Discord API wrapper at the moment.

PR #82 
  
Ex. 
![buttons example](https://user-images.githubusercontent.com/32146663/147448491-1b480ec4-8c60-4ebe-b270-b34e369f90c7.png)

**Comment by BadWolf1023** [comment]
This is something I've wanted to see for a long time. Buttons are powerful and easy for the user. Very, very cool. I am thrilled.

I've always thought Table Bot can be even smarter with buttons, intelligently listing buttons to fix an error that occurred recently, though it's completely up to you or ForestMKW if you want to do it. So for example, when a table is sent, it alway comes with a "Get Table" (`?wp` equivalent) button. And suppose the last race had a disconnection. Two more buttons could be sent with that table too: `?dc 1 on` or `?dc 1 before`, though those buttons could be better named perhaps as `Bad Wolf DCed before R4` and `Bad Wolf DCed during R4`.

This is a simple example of suggested buttons, but given a certain error, even complicated ones, Table Bot can know the command(s) to fix it and could suggest them via buttons (blank times, some large times, ties, etc).

Buttons can also be used to create more exposure for new or underused commands, and even to teach users (eg users commonly use `?dc 1 before` when a blank time occurs, which is not correct, so `?changeroomsize 4 11` is the button that is sent with the table to teach people).

These are all just my ideas of where this could go if you wanted to push the button development! What are your thoughts?

**Comment by camelwater** [comment]
Yeah, that's a really good idea; I hadn't thought about using the buttons like you've described to recommend error fixing.

I've thought about perhaps putting select menus to select which player (like in the example you described for clarifying whether someone DCed during or before the race), but the way you've described is probably much more intuitive for users.

Adding that feature should be pretty straightforward since I think Table Bot already gives integer classifications to all the errors, and it would definitely improve user experience like you said as it would almost entirely get rid of the need for user commands. 

I will be looking to implement these ideas next for sure.

**Comment by camelwater** [comment]
Merged into production branch.
